services:
  apigateway:
    build:
      context: .
      dockerfile: ApiGateway/OcelotApiGateway/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "5165:5165"
    depends_on:
      - inventoryservice
      - productcatalogservice
    networks:
      - microservices-network

  inventoryservice:
    build:
      context: .
      dockerfile: APIs/InventoryService/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "5105:5105"
    networks:
      - microservices-network

  productcatalogservice:
    build:
      context: .
      dockerfile: APIs/ProductCatalogService/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "5106:5106"
    networks:
      - microservices-network

networks:
  microservices-network:
    driver: bridge
